print("##############################")
print("#                            #")
print("#    Ryan Muhammad Irfan     #")
print("#        220817310013        #")
print("#                            #")
print("##############################")